environments:
  dev:
    envName: dev
    webUrl: http://www.kotuszkowo.pl
    title: Kotuszkowo- blog o kotach
    browser: chrome
    active: n
  test:
    envName: test
    webUrl: http://146.59.32.4/
    title: TesterSii
    browser: chrome
    active: y

